### ISSUE TITLE
10 day trial is over in less than 24 hours.

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#128] opened 2017-05-19 15:51 UTC
I have two customers that have been trying out the latest build of TG Pro (2.20) with Paddle 3.0.18 and they are complaining that the 10 day trial runs out after 10 hours (for customer #1) and 24 hours (for customer #2).

What the heck could be going on and is there something that needs to be fixed?

**Comment by OskarGroth** [comment] 2017-05-29 09:27
I am also seeing issues with Trial functionality. After some restarts of the app I get this:

<img width="547" alt="screen" src="https://cloud.githubusercontent.com/assets/1417019/26544325/b42fe2f0-4461-11e7-9efc-f8919a39576e.png">

Which should be an unreachable state (Trial remaining but also expired - no "Continue" button)

**Comment by avalore** [comment] 2017-05-29 09:56
What version of the SDK is being used?
Could you please email a copy of the files below so we can look further into this?
`~/Library/Application Support/App Name/paddata.padl` (if not sandboxed)
`~/.product_id.padl`(replacing `product_id` with your Paddle product id)

**Comment by tunabelly** [comment] 2017-05-29 13:10
Again, this is with Paddle 3.0.18 and there's no way I can ask the now non-customers to send the files since they are already upset enough that they couldn't actually try out the app (and they never bought it). 

And I had another person email me about this on the weekend. Usually if someone emails about an issue like this, there are usually between 10-100 people that don't email. So we're loosing a LOT of potential sales.

**Comment by tunabelly** [comment] 2017-05-30 14:46
I just had another customer email:

"Why is it showing Trial Over when I sill have 9 days left. 
I used it for 1 day and the next day it’s over."

This is one of the biggest showstoppers I've seen with Paddle and this needs a fix asap.

**Comment by OskarGroth** [comment] 2017-05-30 17:42
I've emailed you the files.
For me the issue has gone away on subsequent launches of the app so I'm not so sure if my files are useful. At the point of grabbing the files the Trial worked as expected. It is only on certain occasions I've ended up with the situation described above.

If the issue is intermittent it would explain why this randomly happens to a subset of customers. Maybe it could be resolved for them as well by restarting the app, however most users are not tech-savvy enough to try that on their own initiative. Trial functionality needs to work 100%, for everyone, always.

The combination of reaching an unreachable state, on random occasions, solvable by restarting the app, leads me to believe this problem is due to issues as race conditions or incorrect calculations, maybe related to system clock.

Whenever I see this issue again I'll make sure to send you a copy of the files again.

**Comment by avalore** [comment] 2017-05-31 15:14
Thanks @OskarGroth - those files were very useful. We have a fix for this issue that we're putting together.

The issue was around a mismatch between trial start dates resulting from what seems to be a permissions problem, which would explain why additional launches resolved the issue.

**Comment by tunabelly** [comment] 2017-06-02 01:54
Just got another one: "On 5/30/16 I downloaded your software TG Pro to take advantage of the 10 day trial period; I was able to set the temperatures, but today it will not allow me back in to make adjustments. In fact it is causing more problems than before I installed it."

Can't wait to have this fixed!

**Comment by tunabelly** [comment] 2017-06-04 01:44
Got another one: "10 day trail…really….lasted about 30 minutes…and then trial over."

**Comment by tunabelly** [comment] 2017-06-07 12:23
@avalore how's it going with this one?

**Comment by tunabelly** [comment] 2017-06-10 13:28
@involer @avalore we've been waiting for a fix for this and issue #127.  And I've sent multiple emails to see what's going on with no reply.

Waiting 22 days for this and 26 days for #127 is too long for showstoppers.

**Comment by tunabelly** [comment] 2017-06-10 13:31
To make this even worse we have an update that needs to go out for TG Pro with important fixes except we're waiting for Paddle 3.0.20 before we ship so that there aren't back to back updates. So we can't ship until this is fixed!

**Comment by avalore** [comment] 2017-06-16 11:53
Are either of you using `resetTrialOnVersionUpdateForMajorOnly:` ?

**Comment by OskarGroth** [comment] 2017-06-16 12:20
Nope. Just a standard startLicensing setup for me.

**Comment by avalore** [comment] 2017-06-16 12:30
Thanks

**Comment by tunabelly** [comment] 2017-06-16 12:32
Same here, just the standard startLicensing, along with the isSiteLicensed = YES which doesn't work (ticketed in #125).

**Comment by GregularExpressions** [comment] 2017-06-22 15:55
Hey @OskarGroth & @tunabelly 

We believe release [v3.0.20](https://github.com/PaddleHQ/Mac-Framework/releases/tag/v3.0.20) prevents this happening in future and a reinstall should resolve for anyone currently experiencing this issue.

Thanks,
Greg.

**Closed** 2017-06-22 15:56 UTC
