### ISSUE TITLE
Crash in Paddle 3.0.0 framework

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework#83] opened 2016-06-09 01:31 UTC
Incident Identifier: 236DC85F-FFC5-4403-884A-493700FDBF58
CrashReporter Key:   67424345-1EF2-5F8F-93FF-161B1B1E5D51
Hardware Model:      MacBookPro12,1
Process:         TG Pro [1264]
Path:            
Identifier:      com.tunabellysoftware.tgpro
Version:         2.9.10 (2772)
Code Type:       X86-64
Parent Process:  launchd [1]

Date/Time:       2016-06-08 15:06:39 +0000
OS Version:      Mac OS X 10.11.5 (15F34)
Report Version:  104

Exception Type:  SIGSEGV
Exception Codes: SEGV_MAPERR at 0x7f99548cad0
Crashed Thread:  0

Application Specific Information:
Selector name found in current argument registers: activityIndicator

Thread 0 Crashed:
0   libobjc.A.dylib                      0x00007fff893df4dd objc_msgSend + 29
1   Paddle                               0x0000000105af5f02 0x105aea000 + 48898
2   WebKitLegacy                         0x00007fff9e7d649b CallFrameLoadDelegate(void (*)(), WebView*, objc_selector*, objc_object*) + 58
3   WebKitLegacy                         0x00007fff9e76a071 WebFrameLoaderClient::dispatchDidFinishLoad() + 80
4   WebCore                              0x00007fff8e6f2b6f WebCore::FrameLoader::checkLoadCompleteForThisFrame() + 590
5   WebCore                              0x00007fff8e6f2856 WebCore::FrameLoader::checkLoadComplete() + 437
6   WebCore                              0x00007fff8e6f573c WebCore::FrameLoader::checkCompleted() + 315
7   WebCore                              0x00007fff8ea24d14 WebCore::CachedResourceLoader::loadDone(WebCore::CachedResource*, bool) + 67
8   WebCore                              0x00007fff8e7583a7 WebCore::SubresourceLoader::notifyDone() + 86
9   WebCore                              0x00007fff8e75795f WebCore::SubresourceLoader::didFinishLoading(double) + 1198
10  CFNetwork                            0x00007fff97fddacd __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 68
11  CFNetwork                            0x00007fff97fdd9e2 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 232
12  CFNetwork                            0x00007fff97fdd8e7 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 47
13  CFNetwork                            0x00007fff97fe2686 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 103
14  CFNetwork                            0x00007fff981774bd ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 99
15  libdispatch.dylib                    0x00007fff8c31d40b _dispatch_client_callout + 7
16  libdispatch.dylib                    0x00007fff8c32b039 _dispatch_block_invoke + 473
17  CFNetwork                            0x00007fff97fdd7a4 RunloopBlockContext::_invoke_block(void const*, void*) + 23
18  CoreFoundation                       0x00007fff97ad4d74 CFArrayApplyFunction + 67
19  CFNetwork                            0x00007fff97fdd69d RunloopBlockContext::perform() + 136
20  CFNetwork                            0x00007fff97fdd53e MultiplexerSource::perform() + 281
21  CFNetwork                            0x00007fff97fdd360 MultiplexerSource::_perform(void*) + 71
22  CoreFoundation                       0x00007fff97b32881 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 16
23  CoreFoundation                       0x00007fff97b11fbc __CFRunLoopDoSources0 + 555
24  CoreFoundation                       0x00007fff97b114df __CFRunLoopRun + 926
25  CoreFoundation                       0x00007fff97b10ed8 CFRunLoopRunSpecific + 295
26  HIToolbox                            0x00007fff89b08935 RunCurrentEventLoopInMode + 234
27  HIToolbox                            0x00007fff89b08677 ReceiveNextEventCommon + 183
28  HIToolbox                            0x00007fff89b085af _BlockUntilNextEventMatchingListInModeWithFilter + 70
29  AppKit                               0x00007fff887cadf6 _DPSNextEvent + 1066
30  AppKit                               0x00007fff887ca226 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 453
31  AppKit                               0x00007fff887bed80 -[NSApplication run] + 681
32  AppKit                               0x00007fff88788368 NSApplicationMain + 1175
33  TG Pro                               0x000000010540c4b4 start + 51

Thread 1:
0   libsystem_kernel.dylib               0x00007fff9d317efa kevent_qos + 10
1   libdispatch.dylib                    0x00007fff8c322dcd _dispatch_mgr_thread + 51

Thread 2:
0   HockeySDK                            0x00000001056ffb54 0x1056c8000 + 228180
1   HockeySDK                            0x0000000105709c73 0x1056c8000 + 269427
2   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
3   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
4   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 3:
0   libsystem_kernel.dylib               0x00007fff9d310f72 mach_msg_trap + 10
1   CoreFoundation                       0x00007fff97b121c4 __CFRunLoopServiceMachPort + 211
2   CoreFoundation                       0x00007fff97b1168c __CFRunLoopRun + 1355
3   CoreFoundation                       0x00007fff97b10ed8 CFRunLoopRunSpecific + 295
4   AppKit                               0x00007fff88920d95 _NSEventThread + 148
5   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
6   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
7   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 4:
0   libsystem_kernel.dylib               0x00007fff9d310f72 mach_msg_trap + 10
1   CoreFoundation                       0x00007fff97b121c4 __CFRunLoopServiceMachPort + 211
2   CoreFoundation                       0x00007fff97b1168c __CFRunLoopRun + 1355
3   CoreFoundation                       0x00007fff97b10ed8 CFRunLoopRunSpecific + 295
4   CFNetwork                            0x00007fff97fb8095 +[NSURLConnection(Loader) _resourceLoadLoop:] + 411
5   Foundation                           0x00007fff9a8bde64 __NSThread__start__ + 1350
6   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
7   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
8   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 5:
0   libsystem_kernel.dylib               0x00007fff9d3175e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8b14f341 start_wqthread + 12

Thread 6:
0   libsystem_kernel.dylib               0x00007fff9d31707a __select + 10
1   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
2   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
3   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 7:
0   libsystem_kernel.dylib               0x00007fff9d3175e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8b14f341 start_wqthread + 12

Thread 8:
0   libsystem_kernel.dylib               0x00007fff9d3175e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8b14f341 start_wqthread + 12

Thread 9:
0   libsystem_kernel.dylib               0x00007fff9d3175e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8b14f341 start_wqthread + 12

Thread 10:
0   libsystem_kernel.dylib               0x00007fff9d3175e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8b14f341 start_wqthread + 12

Thread 11:
0   libsystem_kernel.dylib               0x00007fff9d3175e2 __workq_kernreturn + 10
1   libsystem_pthread.dylib              0x00007fff8b14f341 start_wqthread + 12

Thread 12:
0   ???                                  0x0000000000000000 0x0 + 0

Thread 13:
0   libsystem_kernel.dylib               0x00007fff9d31710a __semwait_signal + 10
1   libc++.1.dylib                       0x00007fff8af32020 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 74
2   JavaScriptCore                       0x00007fff9eee383b bmalloc::Heap::scavenge(std::__1::unique_lock<bmalloc::StaticMutex>&, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l> >) + 154
3   JavaScriptCore                       0x00007fff9eee3494 bmalloc::Heap::concurrentScavenge() + 67
4   JavaScriptCore                       0x00007fff9eee5a1a bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::entryPoint() + 89
5   JavaScriptCore                       0x00007fff9eee59b9 bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::pthreadEntryPoint(void*) + 8
6   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
7   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
8   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 14:
0   libsystem_kernel.dylib               0x00007fff9d316db6 __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aef368f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 46
2   JavaScriptCore                       0x00007fff9e8ba99b JSC::GCThread::waitForNextPhase() + 170
3   JavaScriptCore                       0x00007fff9e8ba7e8 JSC::GCThread::gcThreadMain() + 87
4   JavaScriptCore                       0x00007fff9e8b0162 WTF::threadEntryPoint(void*) + 177
5   JavaScriptCore                       0x00007fff9e8b008f WTF::wtfThreadEntryPoint(void*) + 14
6   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
7   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
8   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 15:
0   libsystem_kernel.dylib               0x00007fff9d316db6 __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aef368f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 46
2   JavaScriptCore                       0x00007fff9e8ba99b JSC::GCThread::waitForNextPhase() + 170
3   JavaScriptCore                       0x00007fff9e8ba7e8 JSC::GCThread::gcThreadMain() + 87
4   JavaScriptCore                       0x00007fff9e8b0162 WTF::threadEntryPoint(void*) + 177
5   JavaScriptCore                       0x00007fff9e8b008f WTF::wtfThreadEntryPoint(void*) + 14
6   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
7   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
8   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 16:
0   libsystem_kernel.dylib               0x00007fff9d316db6 __psynch_cvwait + 10
1   libc++.1.dylib                       0x00007fff8aef368f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 46
2   JavaScriptCore                       0x00007fff9e8ba99b JSC::GCThread::waitForNextPhase() + 170
3   JavaScriptCore                       0x00007fff9e8ba7e8 JSC::GCThread::gcThreadMain() + 87
4   JavaScriptCore                       0x00007fff9e8b0162 WTF::threadEntryPoint(void*) + 177
5   JavaScriptCore                       0x00007fff9e8b008f WTF::wtfThreadEntryPoint(void*) + 14
6   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
7   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
8   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 17:
0   libsystem_kernel.dylib               0x00007fff9d316db6 __psynch_cvwait + 10
1   JavaScriptCore                       0x00007fff9ec101bb JSC::DFG::Worklist::runThread(JSC::DFG::ThreadData*) + 234
2   JavaScriptCore                       0x00007fff9e8b0162 WTF::threadEntryPoint(void*) + 177
3   JavaScriptCore                       0x00007fff9e8b008f WTF::wtfThreadEntryPoint(void*) + 14
4   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
5   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
6   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 18:
0   libsystem_kernel.dylib               0x00007fff9d316db6 __psynch_cvwait + 10
1   JavaScriptCore                       0x00007fff9e8ba66f WTF::ThreadCondition::timedWait(WTF::Mutex&, double) + 62
2   WebKitLegacy                         0x00007fff9e80f090 std::__1::unique_ptr<std::__1::function<void ()>, std::__1::default_delete<std::__1::function<void ()> > > WTF::MessageQueue<std::__1::function<void ()> >::waitForMessageFilteredWithTimeout<WTF::MessageQueue<std::__1::function<void ()> >::waitForMessage()::'lambda'(std::__1::function<void ()> const&)>(WTF::MessageQueueWaitResult&, WTF::MessageQueue<std::__1::function<void ()> >::waitForMessage()::'lambda'(std::__1::function<void ()> const&)&&, double) + 79
3   WebKitLegacy                         0x00007fff9e80e808 WebCore::StorageThread::threadEntryPoint() + 183
4   JavaScriptCore                       0x00007fff9e8b0162 WTF::threadEntryPoint(void*) + 177
5   JavaScriptCore                       0x00007fff9e8b008f WTF::wtfThreadEntryPoint(void*) + 14
6   libsystem_pthread.dylib              0x00007fff8b15199d _pthread_body + 130
7   libsystem_pthread.dylib              0x00007fff8b15191a _pthread_start + 167
8   libsystem_pthread.dylib              0x00007fff8b14f351 thread_start + 12

Thread 0 crashed with X86-64 Thread State:
   rip: 0x00007fff893df4dd    rbp: 0x00007fff5a7f3d00    rsp: 0x00007fff5a7f3b78    rax: 0x00007f9954a61ae0 
   rbx: 0x0000000105af5ea0    rcx: 0x0100000000000000    rdx: 0x011dffff7ccdff49    rdi: 0x00007f9954a61ae0 
   rsi: 0x0000000105b35eea     r8: 0x0000000000000040     r9: 0x00007f995260b0c8    r10: 0x0000000105b35eea 
   r11: 0x000007f99548cab8    r12: 0x00007fff5a7f3e08    r13: 0x000000010fef7090    r14: 0x00007f9954a765c0 
   r15: 0x00007fff959ff86f rflags: 0x0000000000010206     cs: 0x000000000000002b     fs: 0x0000000000000000 
    gs: 0x0000000000000000 

Binary Images:
       0x10540a000 -        0x1055d4fff +TG Pro x86_64  <9bcc5bd9e35d3d928044158ed5479d8b> /Applications/TG Pro.app/Contents/MacOS/TG Pro
       0x10564e000 -        0x10568afff +Sparkle x86_64  <852faba7327631e785d48182810549d3> /Applications/TG Pro.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x1056c8000 -        0x105741fff +HockeySDK x86_64  <ec747b3c129c3124a2865ab8b4fd4881> /Applications/TG Pro.app/Contents/Frameworks/HockeySDK.framework/Versions/A/HockeySDK
       0x1057c9000 -        0x10592efff +MailCore x86_64  <e95e964f40f93f2883ed8201b37b67f2> /Applications/TG Pro.app/Contents/Frameworks/MailCore.framework/Versions/A/MailCore
       0x105aea000 -        0x105b47fff +Paddle x86_64  <9197c99131233401a8c328585d5e7605> /Applications/TG Pro.app/Contents/Frameworks/Paddle.framework/Versions/A/Paddle

**Comment by henderea** [comment] 2016-06-09 12:29
3.0.1 says it fixes a purchase view crash.  Have you tested if the issue is fixed?  I haven't upgraded my app to 3.x yet, and I think I'll probably wait for some issues to be sorted out.

**Comment by avalore** [comment] 2016-06-09 17:40
This has indeed been fixed in 3.0.1. It was related to a delegate of a WebView inadvertently being retained.

**Closed by avalore** 2016-06-09 17:40 UTC
